CREATE TABLE addresses
(
  address_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT address_pk PRIMARY KEY,
  street VARCHAR2 (20 CHAR) NOT NULL ,
  street_num NUMBER (4) NOT NULL,
  city VARCHAR2(20 CHAR) NOT NULL
);


CREATE TABLE libraries
(
  library_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT libraries_pk PRIMARY KEY,
  name VARCHAR2 (30 CHAR) NOT NULL ,
  address_id NUMBER NOT NULL REFERENCES addresses (address_id),
  phone_number NUMBER (9) NOT NULL
);

Create Table work_times
(
    work_times_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT work_time_pk PRIMARY KEY,
    library_id NUMBER NOT NULL REFERENCES libraries (library_id),
    day Number (1) NOT NULL,
    opening VARCHAR2 (5 CHAR) NOT NULL,
    closing VARCHAR2 (5 CHAR) NOT NULL
);

CREATE TABLE authors
(
  author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT author_pk PRIMARY KEY,
  name VARCHAR2 (20 CHAR) NOT NULL ,
  surname VARCHAR2 (20 CHAR) NOT NULL ,
  birth_date DATE,
  nationality VARCHAR2 (20 CHAR)
);


CREATE TABLE books
(
  book_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT book_pk PRIMARY KEY,
  title VARCHAR2 (40 CHAR) NOT NULL ,
  author_id NUMBER NOT NULL REFERENCES authors (author_id),
  pages NUMBER NOT NULL,
  isbn NUMBER (13) NOT NULL,
  year NUMBER NOT NULL,
  genre VARCHAR2 (20 CHAR) NOT NULL
);

 CREATE TABLE copies
(
  copy_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT copy_pk PRIMARY KEY,
  library_id NUMBER NOT NULL REFERENCES libraries (library_id),
  book_id NUMBER NOT NULL REFERENCES books (book_id),
  is_available NUMBER NOT NULL
);

  CREATE TABLE users_data
(
  user_data_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT user_data_pk PRIMARY KEY,
  login VARCHAR2 (15 CHAR) NOT NULL ,
  password VARCHAR2 (15 CHAR) NOT NULL ,
  is_admin NUMBER NOT NULL
);

  CREATE TABLE users
(
  user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT user_pk PRIMARY KEY,
  user_data_id NUMBER NOT NULL REFERENCES users_data (user_data_id),
  name VARCHAR2 (20 CHAR) NOT NULL ,
  surname VARCHAR2 (20 CHAR) NOT NULL
);

 CREATE TABLE penalties
(
  penalty_id NUMBER CONSTRAINT penalty_pk PRIMARY KEY,
  name VARCHAR2 (20 CHAR) NOT NULL ,
  description VARCHAR2 (100 CHAR) NOT NULL ,
  value NUMBER NOT NULL
);

CREATE TABLE penalties_history
(
  penalty_history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT penalty_history_pk PRIMARY KEY,
  penalty_id NUMBER NOT NULL REFERENCES penalties (penalty_id),
  user_id NUMBER NOT NULL REFERENCES users (user_id),
  is_paid NUMBER NOT NULL
);

 CREATE TABLE orders
(
  order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT order_pk PRIMARY KEY,
  copy_id NUMBER NOT NULL REFERENCES copies (copy_id),
  date_borrow DATE,
  date_return DATE
);

 CREATE TABLE orders_history
(
  order_history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT order_history_pk PRIMARY KEY,
  order_id NUMBER NOT NULL REFERENCES orders (order_id),
  user_id NUMBER NOT NULL REFERENCES users (user_id),
  status VARCHAR2 (20 CHAR) NOT NULL
);

COMMIT;